version: '3.8'

services:
  server:
    build: ./Server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/usersaccs
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=usersaccs
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./Server:/app
    networks:
      - app-network

  client:
    build: ./Client
    ports:
      - "5173:5173"
    depends_on:
      server:
        condition: service_healthy
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - app-network

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: usersaccs
      POSTGRES_INITDB_ARGS: "--auth=md5"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

volumes:
  postgres-data:

networks:
  app-network:
